// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ocasdoyluytmuuswelym.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9jYXNkb3lsdXl0bXV1c3dlbHltIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE3ODc3MTUsImV4cCI6MjA2NzM2MzcxNX0.EXl3JR_Cr9OvTy0Kpx4ORhLBfFLwMw6t3aA4aYZXUfE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});